django authentication/second_project/login_app/urls.py
from django.urls import path
from login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = 'login_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('user_form/',views.userform, name='user_form'),
    path('login_page/',views.login_page, name='login_page'),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/',views.logout_page, name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django authentication/second_project/second_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('login_app.urls')),
]

django authentication/second_project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

django authentication/second_project/login_app/forms.py
from django.contrib.auth.models import User
from login_app.models import UserInfo
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password','email']

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ["facebook_id","profile_pic"]     

django authentication/second_project/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm,UserInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from login_app.models import UserInfo

# Create your views here.
def login_page(request):
    diction = {}
    return render(request,'login_app/login.html',context=diction)

def user_login(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("login_app:index"))
            else:
                return HttpResponse("Account is not active!")
        else:
            return HttpResponse("Username or password is wrong!")
    return HttpResponseRedirect(reverse('login_app:login_page'))

@login_required
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_app:login_page'))

def index(request):
    diction = {}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id 
        user_basic_form = User.objects.get(pk=user_id)
        user_more_form = UserInfo.objects.get(user__pk=user_id)
        diction = {'basic_form':user_basic_form, 'more_info_form':user_more_form}
        
    return render(request,'login_app/index.html',context=diction)

def userform(request):
    registered = False
    if request.method =='POST':
        userform = UserForm(data=request.POST)
        userinfoForm = UserInfoForm(data=request.POST)
        if userform.is_valid() and userinfoForm.is_valid():
            user = userform.save()
            user.set_password(user.password)
            user.save()

            usercustomForm = userinfoForm.save(commit=False)
            usercustomForm.user=user
            if 'profile_pic' in request.FILES:
                usercustomForm.profile_pic = request.FILES['profile_pic']
            usercustomForm.save()
            registered=True    
    else:
        userform = UserForm()
        userinfoForm = UserInfoForm()
    diction = {'userform':userform,'userinfoform':userinfoForm,'registered':registered}
    return render(request,'login_app/userform.html',context=diction)

django authentication/second_project/templates/login_app/base.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
	<title>{{title}}</title>
</head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                {% if request.user.is_authenticated %}
                <a class="nav-link active" aria-current="page" href="{% url "login_app:index" %}">Home</a>
                <a class="nav-link" href="{% url "login_app:logout" %}">Logout</a>
                {% else %}
                <a class="nav-link" href="{% url "login_app:user_form" %}">Register Form</a>
                <a class="nav-link" href="{% url "login_app:login_page" %}">Login</a>
                {% endif %}
            </div>
            </div>
        </nav>
    <div class="container" style="padding-top:20px">
        {% block body %}
        
        {% endblock body %}
    </div>
    </body>
</html>

django authentication/second_project/templates/login_app/index.html
{% extends "login_app/base.html" %}
{% block body %}
<h2>This text is index page</h2>

<p>Username:{{basic_form.username}}</p>
<p>Email:{{basic_form.email}}</p>
<p><a href="{{more_info_form.facebook_id}}">Facebook</a></p>
<img src="/media/{{more_info_form.profile_pic}}" width="100px"/>


{% endblock body %}

django authentication/second_project/templates/login_app/login.html
{% extends "login_app/base.html" %}
{% block body %}
<h3>Log in page</h3>
<form action="{% url "login_app:user_login" %}" method='POST' >
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" class="form-control" placeholder="Enter Username" required>
    <label for="password">Password:</label>
    <input type="password" name="password" class="form-control" placeholder="Enter Password" required>
    <br>
    <input type="submit" name="submit" value="submit">
    
</form>
{% endblock body %}

django authentication/second_project/templates/login_app/userform.html
{% extends "login_app/base.html" %}
{% block body %}
<h1>User Creation Form</h1>
{% if registered %}
<div class="alert alert-success">Registered Successfull!!</div>
{% else %}
<form enctype="multipart/form-data" method='POST'>
    {% csrf_token %}
    {{userform.as_p}}
    {{userinfoform.as_p}}
    <input type="submit" name="submit" value="Register">
</form>
{% endif %}
{% endblock body %}